#!/usr/bin/env node

/**
 * Self-host the three Google Fonts so the page makes no render-blocking
 * third-party request. Fetches the Google Fonts CSS (which, with a modern
 * browser UA, serves woff2), keeps only the `latin` and `latin-ext` subsets
 * (latin-ext covers Polish diacritics), downloads each woff2 into `fonts/`,
 * and writes a local `fonts/fonts.css` with rewritten URLs and `font-display:
 * swap` preserved.
 *
 * Re-run whenever the font set changes:
 *   node scripts/fetch-fonts.js
 *
 * Then rebuild (`node scripts/build-catalog.js`) — the template links
 * `fonts/fonts.css` instead of fonts.googleapis.com.
 */

const fs = require('node:fs');
const path = require('node:path');

const FONTS_DIR = path.resolve(__dirname, '..', 'fonts');
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Cormorant+Garamond:wght@400;500;600' +
  '&family=Inter:wght@400;500;600' +
  '&family=Press+Start+2P' +
  '&display=swap';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

function slugify(value) {
  return String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function main() {
  fs.mkdirSync(FONTS_DIR, { recursive: true });

  const css = await (await fetch(CSS_URL, { headers: { 'user-agent': UA } })).text();

  // Google emits `/* <subset> */` immediately before each @font-face block.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (blocks.length === 0) {
    throw new Error('No @font-face blocks parsed — did the CSS format change?');
  }

  const chunks = [];
  for (const [, subset, block] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) {
      continue;
    }
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
    const urlMatch = block.match(/url\((https:[^)]+\.woff2)\)/);
    if (!urlMatch) {
      continue;
    }

    const fileName = `${slugify(family)}-${weight}-${subset}.woff2`;
    const buffer = Buffer.from(await (await fetch(urlMatch[1])).arrayBuffer());
    fs.writeFileSync(path.join(FONTS_DIR, fileName), buffer);
    chunks.push(`/* ${subset} */\n${block.replace(urlMatch[0], `url(${fileName})`)}`);
    console.log(`saved ${fileName} (${buffer.length} bytes)`);
  }

  const header =
    '/* Self-hosted Google Fonts — latin + latin-ext only.\n' +
    '   Generated by scripts/fetch-fonts.js. Do not edit by hand. */\n\n';
  fs.writeFileSync(path.join(FONTS_DIR, 'fonts.css'), header + chunks.join('\n\n') + '\n', 'utf8');
  console.log(`\nwrote fonts/fonts.css with ${chunks.length} @font-face block(s)`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
